# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5464c15e5c0a630fac6028bfe4c74b3dfcad3642f43b6b56fff42f6b06091a42a59368de20ae1135099775e672a3f385666881062bde81654147bc06091177ea

test:
  secret_key_base: 624107697fe45d421d0cda9043c5f13e42b2e5d566b3e36021841d1a14d3a7296ce3f9b7d4cfdb9096c5ea739e606c4db4ae60d943855d6f83e49882379ac83c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
